name: publish docker image to GH repo


on: [push]


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get short SHA
        id: slug
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Build and push itsxpress image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:docker-images/"
          push: true
          tags: ghcr.io/usda-ars-gbru/itsxpress:sha-${{ env.SHORT_SHA }}
