name: GitHub Actions Weekly Build (V2)

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 */7 * *"
    
jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v4
    - name: Check out Repo
      uses: actions/setup-python@v5
      with:
        python-version: 3.9.19
    - name: Initiate conda channels
      uses: conda-incubator/setup-miniconda@v3
      with:
        channels: conda-forge,bioconda,default
    - name: Initialize conda
      run: |
        conda info
    - name: Set up QIIME Conda environment
      run: |
        conda env create -n testenv --file=https://data.qiime2.org/distro/amplicon/qiime2-amplicon-2024.5-py39-linux-conda.yml
    - name: Install Dependencies
      run: |
        conda activate testenv 
        conda install biopython=1.84
        pip install pyzstd
        pip install pytest
        pip install .
    - name: Test with pytest
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
        echo $CONDA_PREFIX
        echo $CONDA_PKGS_DIR
        ECHO $GITHUB_PATH
        $CONDA_PKGS_DIR/pytest 
    - name: Test qiime install
      run: |
        qiime dev refresch-cache
        qiime itsxpress --help

