name: GitHub Actions Weekly Build (V2)

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 */7 * *"
    
jobs:
  build-linux:
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v4
    - name: Check out Repo
      uses: actions/setup-python@v5
      with:
        python-version: 3.9.19
    - name: Initiate conda channels
      uses: conda-incubator/setup-miniconda@v3
      with:
        channels: conda-forge,bioconda,default
        auto-activate-base: true
    - name: Initialize conda
      run: |
        conda info
    - name: Set up QIIME Conda environment
      run: |
        conda env create -n testenv --file=https://data.qiime2.org/distro/amplicon/qiime2-amplicon-2024.5-py39-linux-conda.yml
    - name: Install Dependencies
      run: |
        conda activate testenv 
        conda install biopython=1.84
        pip install pyzstd
        pip install pytest
        pip install .
    - name: Test with pytest
      run: |
        conda activate testenv
        pytest 
    - name: Test qiime install
      run: |
        conda activate testenv
        #qiime dev refresch-cache
        qiime itsxpress --help

