name: GitHub Actions Weekly Build (V2)

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 */7 * *"
    
jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 398
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
    - run:   |
        #sudo apt update
        #sudo apt install gcc-10 g++-10
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        echo $CONDA_PREFIX
        $CONDA/bin/conda list
        $CONDA/bin/conda info --base
        conda create --name testenv python=3.9.19
        #CONDA_PREFIX=/usr/share/miniconda/envs/testenv
        $CONDA/bin/conda info
        $CONDA/bin/conda list
        
    - name: Initiate conda channels
      uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge,bioconda,default
        activate-environment: testenv
        auto-activate-base: false


    - name: Set up environment
      run: |
        $CONDA/bin/conda env create -n testenv --file https://data.qiime2.org/distro/amplicon/qiime2-amplicon-2024.5-py39-linux-conda.yml
    - name: Install Dependencies
      run: |
        echo $CONDA_PREFIX
        source activate testenv
        $CONDA/bin/conda install biopython
        pip install pyzstd
        pip install pytest
        pip install .
        qiime
        #itsxpress
        #qiime itsxpress
        #ls

    - name: Test with pytest
      run: |
        source activate testenv
        pytest
